#!/usr/bin/env python3
"""Regenerate android/app/src/main/res/values*/palka_strings.xml.

The Android UI reuses the iOS texts verbatim: every "palka*" key from
Example/Sources/ByeByeDPI/{ru,en}.lproj/Localizable.strings becomes a
snake_case Android string (palkaAutoTitle -> palka_auto_title, %@/%d ->
positional %1$s/%1$d). Android-only strings live in
android/palka-strings/android_{ru,en}.txt as `key=value` lines.

Usage: python3 scripts/sync_android_strings.py
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IOS = os.path.join(ROOT, "Example/Sources/ByeByeDPI")
RES = os.path.join(ROOT, "android/app/src/main/res")
EXTRA = os.path.join(ROOT, "android/palka-strings")


def snake(key):
    s = re.sub(r"(?<!^)(?=[A-Z])", "_", key).lower()
    return s.replace("q_u_i_c", "quic").replace("v_p_n", "vpn").replace("h_t_t_p", "http")


def android_value(value):
    counter = [0]

    def positional(match):
        counter[0] += 1
        return "%%%d$%s" % (counter[0], {"@": "s", "d": "d"}[match.group(1)])

    value = re.sub(r"%(?!%)([@d])", positional, value)
    value = value.replace('\\"', '"')
    value = value.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    value = value.replace("'", "\\'").replace('"', '\\"')
    if value.startswith(("@", "?")):
        value = "\\" + value
    return value


def generate(lang, values_dir):
    lines = [
        '<?xml version="1.0" encoding="utf-8"?>',
        "<!-- Generated by scripts/sync_android_strings.py from the iOS Localizable.strings; do not edit. -->",
        "<resources>",
    ]
    with open(os.path.join(IOS, lang + ".lproj/Localizable.strings"), encoding="utf-8") as src:
        for line in src:
            m = re.match(r'\s*"(palka[^"]+)"\s*=\s*"(.*)";\s*$', line)
            if m:
                lines.append('    <string name="%s">%s</string>' % (snake(m.group(1)), android_value(m.group(2))))
    with open(os.path.join(EXTRA, "android_%s.txt" % lang), encoding="utf-8") as extra:
        for line in extra:
            line = line.rstrip("\n")
            if not line.strip():
                continue
            key, value = line.split("=", 1)
            lines.append('    <string name="%s">%s</string>' % (key.strip(), android_value(value.strip())))
    lines.append("</resources>")
    with open(os.path.join(RES, values_dir, "palka_strings.xml"), "w", encoding="utf-8") as out:
        out.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    generate("ru", "values")
    generate("en", "values-en")
